# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksaver',
            name='href',
            field=models.URLField(),
        ),
    ]
